# Generated by Django 5.0.4 on 2024-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_practice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('big_integer_field', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField(blank=True, null=True)),
                ('char_field', models.CharField(max_length=200)),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=100)),
                ('duration_field', models.DurationField()),
                ('email_field', models.EmailField(max_length=254)),
                ('file_field', models.FileField(upload_to='templates/')),
                ('file_path_filed', models.FilePathField(path='templates/secondapp')),
                ('fload_field', models.FloatField()),
                ('generic_ip_address', models.GenericIPAddressField()),
                ('image_field', models.ImageField(upload_to='templates')),
                ('integer_field', models.IntegerField()),
                ('json_field', models.JSONField()),
                ('positive_big_integer_field', models.PositiveBigIntegerField()),
                ('positive_integer_field', models.PositiveSmallIntegerField()),
                ('slug_field', models.SlugField()),
                ('small_integer', models.SmallIntegerField()),
                ('text_field', models.TextField()),
                ('time_field', models.TimeField()),
                ('url_field', models.URLField()),
                ('uuid_field', models.UUIDField()),
            ],
        ),
    ]
